version: '3.8'

# Tests :
# docker build --target dev -t bc --network host .
# docker run -p 5001:5001 bc python3 main.py -p 5001

services:
  dev_blockchain_node_1:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
      target: dev
    restart: on-failure
    command: python3 main.py -p 5001
    ports:
      - 5001:5001


  dev_blockchain_node_2:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
      target: dev
    restart: on-failure
    command: python3 main.py -p 5002
    ports:
      - 5002:5002


  prod:
    environment:
      PORT: 5002
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: on-failure
    ports:
      - "5002:5002"

  prod_2:
    environment:
      PORT: 5001
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: on-failure
    ports:
      - "5001:5001"

  prod_docker:
    image: "gamestradehub/blockchain-coin_prod:latest"
    restart: on-failure
    ports:
      - "5000:5000"

  prod_docker_2:
    image: "gamestradehub/blockchain-coin_prod:latest"
    restart: on-failure
    ports:
      - 5001:5001

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    restart: on-failure
    command: python3 -m unittest discover -s tests -p 'test_*.py'
    container_name: blockchain_coin_tests


